app:
  name: micro_ads
db:
  adapter: postgresql
  host: localhost
  port: 5432
  user:
  password:
  database: micro_ads
service:
  geocoder:
    url: http://localhost:9294/api/v1
logger:
  path: log/app.log
  level: info
